version: "3"

services:
  jenkins:
    user: root
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    
networks:
  jenkins_network:
    driver: bridge