kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: cluster-in-existing-vpc
  region: eu-north-1
vpc:
  subnets:
    private:
      eu-north-1a: { id: subnet-0ff156e0c4a6d300c }
      eu-north-1b: { id: subnet-0549cdab573695c03 }
      eu-north-1c: { id: subnet-0426fb4a607393184 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: true
  - name: ng-2-workers
    labels: { role: workers }
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
