kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: cluster-in-existing-vpc
  region: us-east-1
vpc:
  id: vpc-0ce2e4f5ca4d03d65
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-08592c29816595efe
      us-east-1b:
        id: subnet-056189bf741ad4a8e
      us-east-1c:
        id: subnet-07bf113f6d926039f

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.large
    desiredCapacity: 1
    privateNetworking: true
  - name: ng-2-workers
    labels: { role: workers }
    instanceType: t3.large
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
