# Start usuario-1 configuration role and roleBinding

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: usuario-1
  name: usuario-1-manager
rules:
- apiGroups: [""]
  verbs: ["get", "watch", "list", "create", "delete", "update"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-namespace-usuario-1
  namespace: usuario-1
subjects:
- kind: User
  name: usuario-1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: usuario-1-manager
  apiGroup: rbac.authorization.k8s.io

---


# Start usuario-2 configuration role and roleBinding

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: usuario-2
  name: usuario-2-manager
rules:
- apiGroups: [""]
  verbs: ["get", "watch", "list", "create", "delete", "update"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-namespace-usuario-2
  namespace: usuario-2
subjects:
- kind: User
  name: usuario-2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: usuario-2-manager
  apiGroup: rbac.authorization.k8s.io
