pipeline {
    parameters{
              string (name: 'testSuite', defaultValue:'', description:'tests executions')
    }
    agent {
        kubernetes {
            containerTemplate {
                name 'maven'
                image 'maven:3.3.9-jdk-8-alpine'
                ttyEnabled true
                command 'cat'
            }
        }
    }
    stages {
        stage("clone-repository"){
            steps{
                container('maven') {
                    echo "Cloning repository..."
                    git credentialsId: 'git_credentials', url: 'https://github.com/luishernandez25/easyTest.git', branch: 'master'
                }
            }
        }
        stage('Run Test'){
            steps{
                container('maven') {
                    echo params.testSuite
                    sh "mvn test -Dtest="+ params.testSuite
                    }
                }
            }
        }
        post {
            failure {
                mail to: 'oldfox255@gmail.com', subject: "The Pipeline for test" +params.testSuite + " has failed!", body: "The Pipeline for test" +params.testSuite + " has failed!"
            }
    }
}